rvm:
  - 2.1.1
branches:
  only:
      - master
before_install:
  - sudo apt-get update
  - sudo apt-get install libqt4-dev
  - "export DISPLAY=:99.0" 
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - cp config/config.yml.example config/config.yml
script:
  - bundle exec rake 


